name: CI Demo

on:
  push:
    branches: [ main ]   # ØºÙŠÙ‘Ø±Ù‡Ø§ Ù„Ùˆ Ø§Ù„ÙØ±Ø¹ Ø¹Ù†Ø¯Ùƒ Ø§Ø³Ù…Ù‡ master
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4   # Ø¯Ù‡ Ø¨ÙŠØ´ØºÙ‘Ù„ Ø§Ù„ÙƒÙˆØ¯ Ø¨ØªØ§Ø¹Ùƒ

      - name: Hello World
        run: echo "Hello Mohammed from GitHub Actions ğŸš€"

      - name: Multi line script
        run: |
          echo "Step 1: build"
          echo "Step 2: test"

