name: CI Demo

on:
  push:
    branches: [ main ]   # Ù„Ùˆ ÙØ±Ø¹Ùƒ Ø§Ù„Ø£Ø³Ø§Ø³Ù‰ master ØºÙŠÙ‘Ø±Ù‡Ø§ Ù„Ù€ master
  workflow_dispatch:      # ØªØ´ØºÙŠÙ„ ÙŠØ¯ÙˆÙ‰ Ù…Ù† UI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4   # Ø§Ù„Ù€ Action Ø§Ù„Ø±Ø³Ù…Ù‰

      - name: Hello World
        run: echo "Hello Mohammed from GitHub Actions ğŸš€"

